ANCHOR_FILE_DOENLOAD_BTN_ID = 'download_source_anchor'
ANCHOR_GENERATED_UTC_CLASS = 'anchor-generated_at'
ANCHOR_FILE_NAME = 'configuration_anchor_{0}_internal_{1}.xml'
ANCHOR_HASH_CLASS = 'anchor-hash'
TRUSTED_ANCHORS_TAB_CSS = 'a[href="#trusted_anchors_tab"]'