LOG_FILE_LOCATION = '/var/log/xroad/audit.log'

LOGIN = 'Log in user'
LOGOUT = 'Log out user'

ADD_GROUP = 'Add group'
ADD_GROUP_FAILED = 'Add group failed'
ADD_ACCESS_RIGHTS_TO_SERVICE = 'Add access rights to service'
ADD_CLIENT = 'Add client'
ADD_CLIENT_FAILED = 'Add client failed'
ADD_MEMBER = 'Add member'
ADD_MEMBER_FAILED = 'Add member failed'
ADD_SECURITY_SERVER = 'Add security server'
ADD_SECURITY_SERVER_FAILED = 'Add security server failed'
ADD_SUBSYSTEM = 'Add subsystem'
ADD_SUBSYSTEM_FAILED = 'Add subsystem failed'
DELETE_CLIENT = 'Delete client'
DELETE_SECURITY_SERVER = "Delete security server"
DELETE_SUBSYSTEM = 'Delete subsystem'
EDIT_MEMBER_NAME_FAILED = 'Edit member name failed'
EDIT_MEMBER_NAME = 'Edit member name'
DELETE_MEMBER = 'Delete member'

ADD_AUTH_CERTIFICATE_FOR_SECURITY_SERVER = 'Add authentication certificate for security server'
ADD_AUTH_CERTIFICATE_FOR_SECURITY_SERVER_FAILED = 'Add authentication certificate for security server failed'
REGISTER_CLIENT = 'Register client'
REGISTER_CLIENT_FAILED = 'Register client failed'
REGISTER_AUTH_CERT = 'Register authentication certificate'
REGISTER_AUTH_CERT_FAILED = 'Register authentication certificate failed'
UNREGISTER_AUTH_CERT = 'Unregister authentication certificate'
UNREGISTER_AUTH_CERT_FAILED = 'Unregister authentication certificate failed'

ADD_WSDL_FAILED = 'Add WSDL failed'
ADD_WSDL = 'Add WSDL'
EDIT_WSDL = 'Edit WSDL'
EDIT_WSDL_FAILED = 'Edit WSDL failed'
EDIT_SERVICE_PARAMS_FAILED = 'Edit service parameters failed'
DELETE_WSDL = 'Delete WSDL'
ENABLE_WSDL = 'Enable WSDL'
DISABLE_WSDL = 'Disable WSDL'
REFRESH_WSDL = 'Refresh WSDL'
DISABLE_WSDL_FAILED = 'Disable WSDL failed'
REFRESH_WSDL_FAILED = 'Refresh WSDL failed'

ADD_GLOBAL_GROUP = 'Add global group'
ADD_GLOBAL_GROUP_FAILED = 'Add global group failed'
ADD_MEMBER_TO_GROUP = 'Add member to global group'
ADD_MEMBER_TO_LOCAL_GROUP = 'Add members to group'
EDIT_GROUP_DESCRIPTION_FAILED = 'Edit group description failed'
EDIT_GROUP_DESCRIPTION = 'Edit group description'
REMOVE_MEMBERS_FROM_GROUP = 'Remove members from group'
DELETE_GROUP = 'Delete group'

ADD_CA = 'Add certification service'
ADD_TS = 'Add timestamping service'
EDIT_TS = 'Edit timestamping service'

ADD_CA_FAILED = 'Add certification service failed'
EDIT_CA = 'Edit certification service settings'
EDIT_CA_FAILED = 'Edit certification service settings failed'
DELETE_CA = 'Delete certification service'
DELETE_TS = 'Delete timestamping service'
ADD_OCSP = 'Add OCSP responder of certification service'
ADD_OCSP_FAILED = 'Add OCSP responder of certification service failed'
EDIT_OCSP = 'Edit OCSP responder'
EDIT_OCSP_FAILED = 'Edit OCSP responder failed'
DISABLE_CERT = 'Disable certificate'

ADD_TS_FAILED = 'Add timestamping service failed'
EDIT_TS_FAILED = 'Edit timestamping service failed'
ADD_TS_EXISTING_URL = 'An approved timestamping service with the inserted URL and certificate already exists'

UNREGISTER_CLIENT = 'Unregister client'
UNREGISTER_CLIENT_FAILED = 'Unregister client failed'
REGISTER_MEMBER_AS_SEC_SERVER_CLIENT = 'Register member as security server client'
REGISTER_MEMBER_AS_SEC_SERVER_CLIENT_FAILED = 'Register member as security server client failed'
REVOKE_CLIENT_REGISTRATION_REQUEST = 'Revoke client registration request'
REVOKE_AUTH_REGISTRATION_REQUEST = 'Revoke authentication certificate request'
APPROVE_CLIENT_REGISTRATION_REQUST = 'Approve registration request'
ADD_MEMBERS_TO_GLOBAL_GROUP = 'Add members to global group'

ADD_INTERNAL_TLS_CERT = 'Add internal TLS certificate'
ADD_INTERNAL_TLS_CERT_FAILED = 'Add internal TLS certificate failed'
DELETE_INTERNAL_TSL_CERT = 'Delete internal TLS certificate'
SET_SERVICE_CONSUMER_CONNECTION_TYPE = 'Set connection type for servers in service consumer role'
EDIT_SERVICE_PARAMS = 'Edit service parameters'

MSG_SERVICE_CENTER = 'X-Road Center UI'
MSG_SERVICE_SECURITY = 'X-Road Proxy UI'

DELETE_TRUSTED_ANCHOR = 'Delete trusted anchor'
ADD_TRUSTED_ANCHOR = 'Add trusted anchor'
ADD_TRUSTED_ANCHOR_FAIL = 'Add trusted anchor failed'
DELETE_KEY_FAIL = 'Delete key failed'
DELETE_KEY = 'Delete key from token and configuration'
DELETE_KEY_FAILED = 'Delete key from token and configuration failed'
GENERATE_KEY = 'Generate key'
GENERATE_KEY_FAILED = 'Generate key failed'
CHANGE_FRIENLY_NAME_FAILED = "Set friendly name to key failed"
CHANGE_FRIENDLY_NAME = 'Set friendly name to key'
GENERATE_CSR = 'Generate CSR'
GENERATE_CSR_FAILED = 'Generate CSR failed'
DELETE_CSR = 'Delete CSR'

ADD_CENTRAL_SERVICE = 'Add central service'
ADD_CENTRAL_SERVICE_FAILED = 'Add central service failed'

EDIT_CENTRAL_SERVICE = 'Edit central service'
EDIT_CENTRAL_SERVICE_FAILED = 'Edit central service failed'

DELETE_CENTRAL_SERVICE = 'Delete central service'

ADD_ACCESS_RIGHTS_TO_SUBJECT = 'Add access rights to subject'
REMOVE_ACCESS_RIGHTS_FROM_SUBJECT = 'Remove access rights from subject'
REMOVE_ACCESS_RIGHTS_FROM_SERVICE = 'Remove access rights from service'
REMOVE_MEMBERS_FROM_GLOBAL_GROUP = 'Remove members from global group'
EDIT_GLOBAL_GROUP_DESCRIPTION = 'Edit global group description'
EDIT_GLOBAL_GROUP_DESCRIPTION_FAILED = 'Edit global group description failed'

GENERATE_TLS_KEY_AND_CERT = 'Generate new internal TLS key and certificate'
SS_BACKUP_SCRIPT_CREATED = 'Configuration backup created'
SS_BACKUP_CONFIGURATION = 'Back up configuration'
SS_BACKUP_CONFIGURATION_FAILED = 'Back up configuration failed'

IMPORT_CERTIFICATE_FROM_TOKEN = 'Import certificate from token'
IMPORT_CERTIFICATE_FROM_TOKEN_FAILED = 'Import certificate from token failed'
IMPORT_CERTIFICATE_FROM_FILE_FAILED = 'Import certificate from file failed'
IMPORT_CERTIFICATE_FROM_FILE = 'Import certificate from file'

ENABLE_CERTIFICATE = 'Enable certificate'

SS_BACKUP_FILE_DELETE = 'Delete backup file'
SS_BACKUP_NEW_FILE_UPLOAD = 'New backup file uploaded successfully'
KEYS_AND_SERTIFICATES_SET_TOKEN = 'Set friendly name to token'
KEYS_AND_SERTIFICATES_SET_TOKEN_FAILED = 'Set friendly name to token failed'
SOFTTOKEN_LOGIN_FAILED = 'Log in to token failed'
SOFTTOKEN_LOGIN_SUCCESS = 'Log in to token'
TOKEN_LOG_OUT = 'Log out from token'
HARDTOKEN_LOG_OUT_FAILED = 'Log out from token failed'

SKIP_UNREG_OF_AUTH_CERT = 'Skip unregistration of authentication certificate'

DELETE_AUTH_CERT = 'Delete authentication certificate of security server'
DELETE_CERT = 'Delete certificate from configuration'

DELETE_GLOBAL_GROUP = 'Delete global group'
REGISTER_MANAGEMENT_SERVICE_PROVIDER = 'Register management service provider as security server client'
EDIT_MANAGEMENT_SERVICE_PROVIDER = 'Edit provider of management services'
DECLINE_REGISTRATION_REQUEST = 'Decline registration request'
REMOVE_MEMBER_FROM_GLOBAL_GROUP = 'Remove member from global group'
ADD_INTERMEDIATE_CA = 'Add intermediate CA'
ADD_INTERMEDIATE_CA_FAILED = 'Add intermediate CA failed'
ADD_INTERMEDIATE_CA_OCSP = 'Add OCSP responder of intermediate CA'
DELETE_INTERMEDIATE_CA = 'Delete intermediate CA'
DELETE_SS_CLIENT = 'Unregister member as security server client'