CLIENTS_BTN_CSS = 'a[href="/clients"]'
SYSTEM_PARAMETERS_BTN_CSS = 'a[href="/sysparams"]'
SYSTEM_SETTINGS_BTN_CSS = 'a[href="/system_settings"]'
KEYSANDCERTIFICATES_BTN_CSS = 'a[href="/keys"]'
BACKUP_AND_RESTORE_BTN_CSS = 'a[href="/backup"]'
BACKUP_AND_UPLOAD_BTN_CSS = 'a[href="/backup_upload"]'
DIAGNOSTICS_BTN_CSS = 'a[href="/diagnostics"]'
VERSION_BTN_CSS = 'a[href="/about"]'

MEMBERS_CSS = 'a[href="/"]'
SECURITY_SERVERS_CSS = 'a[href="/securityservers"]'
GLOBAL_GROUPS_CSS = 'a[href="/groups"]'
CENTRAL_SERVICES_CSS = 'a[href="/central_services"]'
MANAGEMENT_REQUESTS_CSS = 'a[href="/requests"]'
CERTIFICATION_SERVICES_CSS = 'a[href="/approved_cas"]'
TIMESTAMPING_SERVICES_CSS = 'a[href="/tsps"]'
GLOBAL_CONFIGURATION_CSS = 'a[href="/configuration_management"]'